### PR TITLE
Always pass (empty) overrides, interfaces

### LINKED ISSUE #98: aws-cdk 1.19.0 deps break the basic example (can't eval (App))
When running the following code with 1.19.0 versions of the aws-cdk deps:

```clojure
(ns com.latacora.transgressor.cdk
  (:require [stedi.cdk.alpha :as cdk]))

(cdk/import [[App Stack] :from "@aws-cdk/core"])
(def app (App))
```

The failing expression is `(App)` with the following error message:

```
Execution error (IllegalArgumentException) at stedi.jsii.alpha.client/create-object (client.clj:55).
No matching method createObject found taking 2 args for class software.amazon.jsii.JsiiClient
```

Here's the `(pst)`:

```
IllegalArgumentException No matching method createObject found taking 2 args for class software.amazon.jsii.JsiiClient
	clojure.lang.Reflector.invokeMatchingMethod (Reflector.java:127)
	clojure.lang.Reflector.invokeInstanceMethod (Reflector.java:102)
	stedi.jsii.alpha.client/create-object (client.clj:55)
	stedi.jsii.alpha.client/create-object (client.clj:52)
	stedi.jsii.alpha.impl/create (impl.clj:153)
	stedi.jsii.alpha.impl/create (impl.clj:150)
	stedi.jsii.alpha.import/intern-initializer/fn--12748 (import.clj:39)
	clojure.spec.test.alpha/spec-checking-fn/fn--3026 (alpha.clj:142)
	clojure.lang.Var.applyTo (Var.java:705)
	clojure.core/apply (core.clj:665)
	clojure.core/apply (core.clj:660)
	stedi.jsii.alpha.impl/call-initializer (impl.clj:89)
```

### PR DESCRIPTION
**Pull request by lvh**
Fixes #98, though unfortunately not in a backwards-compatible way.

### CODE REVIEW

**Comment by lvh** [comment]
I don't understand the lint failure at all: it appears to run once correctly, and then gets a 403 (?) on the second run.

**Comment by lvh** [comment]
I'm getting a different interesting failure because cdk-clj requires Clojure 1.10+ (because `requiring-resolve`) and deps.edn doesn't specify it:

```
$ clojure -A:dev:test -Stree -Srepro | grep "org.clojure/clojure "   
org.clojure/clojure 1.9.0
```

... so I'm adding it in this PR as well.

**Comment by lvh** [comment]
The remaining test failure in the PR looks promising, but the tests just time out for me locally. May be a Graal thing.

**Comment by lvh** [comment]
FWIW I don't think I missed any linting, I expect the problem is maybe because this is a PR from a fork?

```
$ clj -A:dev:lint
linting took 421ms, errors: 0, warnings: 0
```

**Comment by tvanhens** [comment]
It looks like the linter GitHub action is broken. Will disable for now.

**Comment by tvanhens** [comment]
> Fixes #98, though unfortunately not in a backwards-compatible way.

I'm not sure there is a backwards compatible way of fixing this one since the breakage is in the Jsii protocol itself. Will think on it tonight.

**Comment by lvh** [comment]
@tvanhens the ways I thought of to make this work are by using reflection to figure out what the upstream class supports. But given the experimental nature of a lot of CDK/jsii and the ostensibly implementation detail nature of some of the APis you're calling (no mention in the changelog!) adding a stack of workarounds seems like an inadvisable idea.

Perhaps a minimal feature level detection thing would make sense? Either by checking a version somehow and complaining early if you use one incompatible with it? (Or just accept the problem and tell people to use recent versions of CDK, which is my personal preference.)

**Comment by tvanhens** [comment]
> @tvanhens the ways I thought of to make this work are by using reflection to figure out what the upstream class supports. But given the experimental nature of a lot of CDK/jsii and the ostensibly implementation detail nature of some of the APis you're calling (no mention in the changelog!) adding a stack of workarounds seems like an inadvisable idea.
> 
> Perhaps a minimal feature level detection thing would make sense? Either by checking a version somehow and complaining early if you use one incompatible with it? (Or just accept the problem and tell people to use recent versions of CDK, which is my personal preference.)

I think the latter makes sense in light of the churn in the jsii dependency right now.

**Pull request merged**
